presentation: {
  cli: {
    move-window: {
      "left"
      "right"
    }
  }
}

infrastructure: {
  adapters: {
    sway
  }
}

application: {
  use-cases: {
    "move-window": "move-window(direction)"
    # direction: left | right
  }
  ports: {
    window-manager
  }
}

presentation.cli.move-window."left" -> application.use-cases.move-window
presentation.cli.move-window."right" -> application.use-cases.move-window

application.use-cases.move-window -> application.ports.window-manager

infrastructure.adapters.sway -> application.ports.window-manager
