infrastructure: {
  cli: {
    move-window: {
      "left"
      "right"
    }
  }
  adapters: {
    sway
  }
}

application: {
  use-cases: {
    "move-window (direction)"
  }
  ports: {
    window-manager
  }
}

infrastructure.cli.move-window."left" -> application.use-cases."move-window (direction)"
infrastructure.cli.move-window."right" -> application.use-cases."move-window (direction)"

application.use-cases."move-window (direction)" -> application.ports.window-manager

infrastructure.cli.move-window."left" -> infrastructure.adapters.sway
infrastructure.cli.move-window."right" -> infrastructure.adapters.sway

infrastructure.adapters.sway -> application.ports.window-manager
